### ISSUE TITLE
Symbols for stb style images

### ISSUE THREAD

**Issue by tonitch** [OpenImageDebugger/OpenImageDebugger#312]
### Environment (please complete the following information)

- OID version (commit or tag): fa2f86ec4bdfe423c2731bcc9ab96346527d8708
- OS and Version: arch linux (6.8.7-arch1-1)
- Which debugger [gdb and/or lldb] and respective versions: gdb 14.2
- Python version: 3.11.8

### Describe the bug

I tried to use this software on my code and didn't suceded, so I made a simplified version of my code to try and understand why and I still can't get it to work.

here is the simple code 

```c
#define STB_IMAGE_IMPLEMENTATION
#include <stb/stb_image.h>

int main(void)
{
	int width, heigth, comp;
	unsigned char *data = stbi_load("test.png", &width, &heigth, &comp, 0);
}
```
I break right after the data initialization. I can get all the info I need in gdb by typing `info local` for instance (width, height, comp and data are set)

then when I type `data` in the `add symbols (ctrl+k)` and press enter nothing happen. I also tried with `unsigned char *data` and different "flavours" of it but nothings seems to work 

### To Reproduce

1) get the stb_image.h file from https://github.com/nothings/stb and the above code.
2) compile it using `gcc -O0 -g -o main main.c`
3) `gdb main` and load openimagedebugger using `source <oid.py 's location>`
4) `break 8` & `run`; The oid window open
5) type `data` in the add symbols field

### Actual behavior

Nothing's happening

### Error messages/stack traces

While trying a bunch of things I got gdb to crash twice but I don't really know how to reproduce it.

### Screenshots

![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/26271060/6eb7e3b8-59e6-4284-ae40-94274c7cb57d)
### Additional context

I used -O0 because I though it would be because of optimisation but I tried without it too and it's the same...

ps: on a unrelated note (and if I can make it work) I would like to add this project to the archlinux's user repository (aur) witch would make installing this software more easy on arch's flavour distro. If you want to be comaintainer of the repo just feel free to ask and if there is anything particular to know when packaging this project I would really apreciate to know ^^

**Comment by brunorosa-tomtom** [comment]
Hi, @tonitch, thanks a lot for the well written report, I really appreciate it :)

Getting straight to the point: we currently only support a few opencv and eigen image/matrix classes out of the box. To support other image types, you have to follow https://github.com/OpenImageDebugger/OpenImageDebugger#advanced-configuration . Basically you have to implement a python interface that tells OID how to draw an image. @csantosbh wrote a blog post with more details about it, but I don't remember the link by heart. I will try to find it later.

I would suggest that you try compiling and debugging the testbench project in this repo. There we emulate cv::mat classes. Put a breakpoint on line 351 and you should be able to see the buffer.
Alternatively, you can try to replicate your tests with either opencv or eigen instead of stb.

Regarding arch: I currently have no plans of supporting distros other than Ubuntu since this is mostly a hobby project and I am barely able to properly maintain it as it is... But feel free to go and add it to aur.

> if there is anything particular to know when packaging this project I would really apreciate to know ^^

The tricky part is qt. You gotta read their license very carefully to understand how this affect packaging of OID. Currently the installation relies on having qt installed as shared library (vi apt on ubuntu) and I am not entirely sure if we could just vendor the .so's in a package, for instance.
A suggestion is that you create as an entry point scripts (maybe called `gdb-oid` and `lldb-oid`) that wrap a call to gdb/lldb and import/source oid.py from it.

**Comment by brunoalr** [comment]
Hi, @tonitch, thanks a lot for the well written report, I really appreciate it :)

Getting straight to the point: we currently only support a few opencv and eigen image/matrix classes out of the box. To support other image types, you have to follow https://github.com/OpenImageDebugger/OpenImageDebugger#advanced-configuration . Basically you have to implement a python interface that tells OID how to draw an image. @csantosbh wrote a blog post with more details about it, but I don't remember the link by heart. I will try to find it later.

I would suggest that you try compiling and debugging the testbench project in this repo. There we emulate cv::mat classes. Put a breakpoint on line 351 and you should be able to see the buffer.
Alternatively, you can try to replicate your tests with either opencv or eigen instead of stb.

Regarding arch: I currently have no plans of supporting distros other than Ubuntu since this is mostly a hobby project and I am barely able to properly maintain it as it is... But feel free to go and add it to aur.

> if there is anything particular to know when packaging this project I would really apreciate to know ^^

The tricky part is qt. You gotta read their license very carefully to understand how this affect packaging of OID. Currently the installation relies on having qt installed as shared library (vi apt on ubuntu) and I am not entirely sure if we could just vendor the .so's in a package, for instance.
A suggestion is that you create as an entry point scripts (maybe called `gdb-oid` and `lldb-oid`) that wrap a call to gdb/lldb and import/source oid.py from it.

**Comment by brunoalr** [comment]
Found the blogpost: https://csantosbh.wordpress.com/2016/10/15/configuring-gdb-imagewatch-to-visualize-custom-buffer-types/#more-492

**Comment by tonitch** [comment]
Thanks a lot for you fast response. I'v got a long week end ahead so I will try that next week. The project is really cool and is pretty much exactly what I was looking for (minus the fact that I'm not smart enought to make it work properly haha)

for the packaging, qt is in arch's package already and I have put it as a dependency so this should work properly and I don't think license is a problem as many other repo have it this way :))  (I just finished it : https://aur.archlinux.org/packages/openimagedebugger ) I will certainly do the entry point next week as well ^^

**Comment by tonitch** [comment]
here is my solution for those who need 

`OpenImageDebugger/oidscripts/oidtypes/stb.py`
```py
from oidscripts.oidtypes import interface
from oidscripts.symbols import *

class STBInspector(interface.TypeInspectorInterface):

    def get_buffer_metadata(self,
                            obj_name,  # type: str
                            picked_obj,  # type: DebuggerSymbolReference
                            debugger_bridge  # type: BridgeInterface
                            ):

        width = 9
        height = 9
        comp = 4

        return {"display_name": obj_name,
                "pointer": picked_obj,
                "width": width,
                "height": height,
                "channels": 4,
                "type": OID_TYPES_UINT8,
                "row_stride": width,
                "pixel_layout": "rgba",
                "transpose_buffer": True}

    def is_symbol_observable(self, symbol_obj, symbol_name):
        # type: (DebuggerSymbolReference, str) -> bool
        return (str(symbol_obj.type) == "unsigned char *")
```

I has to be configured for each images but at least it's a start ^^

This project is really awesome and I think a way to improve it would be to configure it on the go. Like there would be a dropdown for each images format existing ( I could make one for raylib) and there would be a custom one where it would be possible to configure each parameter of the above list until you see your image. (I can make a separate and more specific issue if desired)

My "issue" is resolved so I will close it. Thanks for your help!

**Comment by brunoalr** [comment]
Thanks a lot for providing this example!

> Like there would be a dropdown for each images format existing

For supported classes/structs (i.e. scripts under `OpenImageDebugger/oidscripts/oidtypes/`), this is done seamlessly.

> and there would be a custom one where it would be possible to configure each parameter of the above list until you see your image. (I can make a separate and more specific issue if desired)

I think it would be nice to have this idea in a new issue indeed. It is slightly related to
https://github.com/OpenImageDebugger/OpenImageDebugger/issues/30 (a bit old, I know...), but there I was thinking about a command line interface to display "structless" images instead of proper GUI to it.

**Comment by tonitch** [comment]
> For supported classes/structs (i.e. scripts under `OpenImageDebugger/oidscripts/oidtypes/`), this is done seamlessly.

When there is no ambiguity in the type, this is clearly not a problem ^^ I was thinking about multiple specific libs that has similar pattern and couldn't be dissociated ^^ 

> I think it would be nice to have this idea in a new issue indeed. It is slightly related to #30 (a bit old, I know...), but there I was thinking about a command line interface to display "structless" images instead of proper GUI to it.

I will play with oid for a while and then will come back to do that for sure !
